# For public, HTTPS servers.
version: '2.2'

services:

  postgres:
    volumes:
      # TODO: remove this `/mnt/new/` override after returning to single EBS
      - /mnt/new/newpg/dbvol:/var/lib/postgresql/data
      - ../kobo-deployments/postgres/master/postgres.conf:/kobo-docker-scripts/master/postgres.conf
    environment:
      - POSTGRES_BACKUP_FROM_SLAVE=True
    ports:
      - 5432:5432

  mongo:
    ports:
      - 27017:27017

  redis_main:
    ports:
      - 6379:6379

  redis_cache:
    ports:
      - 6380:6380
